windowrulev = suppressevent maximize, class:.* 
windowrulev = tile, class:^(kitty)$
windowrulev = float, class:^(org\.pulseaudio\.pavucontrol)$
windowrulev = float, class:^(nm-connection-editor)$

windowrulev = float, class:^(kitty-btop)$
windowrulev = size 1400 800, class:^(kitty-btop)$
windowrulev = center, class:^(kitty-btop)$

windowrulev = float,class:^(blueman-manager)$
windowrulev = float,class:^(Blueman-manager)$
